<a href="https://colab.research.google.com/github/Ahmadhusyairi17/Disease-Prediction-from-Symptoms/blob/master/notebook/Disease-Prediction-from-Symptoms-checkpoint2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Disease Prediction from Symptoms

For this project, we'll be using the dataset from here: http://people.dbmi.columbia.edu/~friedma/Projects/DiseaseSymptomKB/index.html

Copy the data from all the columns and paste it into an excel sheet -> `raw_data.xlsx`

In [ ]:
# Import Dependencies
import csv                            #melakukan import module csv
import pandas as pd                   #melakukan import module pandas untuk kebutuhan table
import numpy as np                    #melakukan import module numpy untuk array dan matriks
from collections import defaultdict   #melakukan import kelas defauldict dari module collection
import seaborn as sns                 #melakukan import module seaborn untuk kebutuhan visualisasi
import matplotlib.pyplot as plt       #melakukan import matplotlib untuk kebuuhan visualisasi
%matplotlib inline                    #melakukan pengaktifan matplotlib inline untuk kebutuhan menampilkan plot secara otomatis
%matplotlib inline                    #melakukan pengaktifan matplotlib inline untuk kebutuhan menampilkan plot secara otomatis

In [ ]:
# Read Raw Dataset
df = pd.read_excel('/content/raw_data.xlsx')     #membaca file csv/Excel

#terjadi eror karena file raw_data.xlsx tidak terdapat pada drive lokal
#saya melakukan download file raw_data.xlsx terlebih dahulu ada di github
#kemudian simpan ke drive dan masukan lokasi data dalam kurung ('

In [ ]:
df.head()

Disease  Count of Disease Occurrence  \
0  UMLS:C0020538_hypertensive disease                       3363.0   
1                                 NaN                          NaN   
2                                 NaN                          NaN   
3                                 NaN                          NaN   
4                                 NaN                          NaN   

                             Symptom  
0           UMLS:C0008031_pain chest  
1  UMLS:C0392680_shortness of breath  
2            UMLS:C0012833_dizziness  
3             UMLS:C0004093_asthenia  
4                 UMLS:C0085639_fall

In [ ]:
# Fill all NaN with the values above
data = df.fillna(method='ffill')       # untuk mengisi data yang kosong atau hilang (NaN)

In [ ]:
data.head()                            # untuk menampilkan 5 baris pertama dari data yang dimulai dari angka 0

Disease  Count of Disease Occurrence  \
0  UMLS:C0020538_hypertensive disease                       3363.0   
1  UMLS:C0020538_hypertensive disease                       3363.0   
2  UMLS:C0020538_hypertensive disease                       3363.0   
3  UMLS:C0020538_hypertensive disease                       3363.0   
4  UMLS:C0020538_hypertensive disease                       3363.0   

                             Symptom  
0           UMLS:C0008031_pain chest  
1  UMLS:C0392680_shortness of breath  
2            UMLS:C0012833_dizziness  
3             UMLS:C0004093_asthenia  
4                 UMLS:C0085639_fall

In [ ]:
# Process Disease and Symptom Names
def process_data(data):                              #melakukan proses "data" nama penyakit dan gejala
    data_list = []                                   #membuat tempat untuk menampung data array
    data_name = data.replace('^','_').split('_')     #proses merubah tanda dari data
    n = 1
    for names in data_name:
        if (n % 2 == 0):
            data_list.append(names)
        n += 1
    return data_list                                 #menreturn nilai data_list

In [ ]:
# Data Cleanup
disease_list = []
disease_symptom_dict = defaultdict(list)            #menampung data penyakit
disease_symptom_count = {}                          #menampung data list
count = 0                                           #menampung gejala

for idx, row in data.iterrows():                    #melakukan loop data


    # Get the Disease Names
    if (row['Disease'] !="\xc2\xa0") and (row['Disease'] != ""):   #jika row['Disease'] !="\xc2\xa0" dan nilai kolom disease tidak kosong
        disease = row['Disease']
        disease_list = process_data(data=disease)
        count = row['Count of Disease Occurrence']

    # Get the Symptoms Corresponding to Diseases
    if (row['Symptom'] !="\xc2\xa0") and (row['Symptom'] != ""):   #jika row['symptom'] dan nilai kolom symptom tidak kosong
        symptom = row['Symptom']
        symptom_list = process_data(data=symptom)
        for d in disease_list:
            for s in symptom_list:
                disease_symptom_dict[d].append(s)
            disease_symptom_count[d] = count

In [ ]:
# See that the data is Processed Correctly  #untuk memeriksa data apakah diproses dengan benar
disease_symptom_dict

defaultdict(list,
            {'hypertensive disease': ['pain chest',
              'shortness of breath',
              'dizziness',
              'asthenia',
              'fall',
              'syncope',
              'vertigo',
              'sweat',
              'sweating increased',
              'palpitation',
              'nausea',
              'angina pectoris',
              'pressure chest'],
             'diabetes': ['polyuria',
              'polydypsia',
              'shortness of breath',
              'pain chest',
              'asthenia',
              'nausea',
              'orthopnea',
              'rale',
              'sweat',
              'sweating increased',
              'unresponsiveness',
              'mental status changes',
              'vertigo',
              'vomiting',
              'labored breathing'],
             'depression mental': ['feeling suicidal',
              'suicidal',
              'hallucinations auditory',
              'feel

In [ ]:
# Count of Disease Occurence w.r.t each Disease
disease_symptom_count                            #menghitung kemunculan penyakit

{'hypertensive disease': 3363.0,
 'diabetes': 1421.0,
 'depression mental': 1337.0,
 'depressive disorder': 1337.0,
 'coronary arteriosclerosis': 1284.0,
 'coronary heart disease': 1284.0,
 'pneumonia': 1029.0,
 'failure heart congestive': 963.0,
 'accident\xa0cerebrovascular': 885.0,
 'asthma': 835.0,
 'myocardial infarction': 759.0,
 'hypercholesterolemia': 685.0,
 'infection': 630.0,
 'infection urinary tract': 597.0,
 'anemia': 544.0,
 'chronic obstructive airway disease': 524.0,
 'dementia': 504.0,
 'insufficiency renal': 445.0,
 'confusion': 408.0,
 'degenerative\xa0polyarthritis': 405.0,
 'hypothyroidism': 398.0,
 'anxiety state': 390.0,
 'malignant neoplasms': 354.0,
 'primary malignant neoplasm': 354.0,
 'acquired\xa0immuno-deficiency syndrome': 350.0,
 'HIV': 350.0,
 'hiv infections': 350.0,
 'cellulitis': 341.0,
 'gastroesophageal reflux disease': 325.0,
 'septicemia': 311.0,
 'systemic infection': 311.0,
 'sepsis (invertebrate)': 311.0,
 'deep vein thrombosis': 310.0,
 'deh

In [ ]:
# Save cleaned data as CSV
f = open('/content/cleaned_data.csv', 'w')     #membuat file baru untuk menyimpan data cleaned_data.csv


with f:
    writer = csv.writer(f)
    for key, val in disease_symptom_dict.items():
        for i in range(len(val)):
            writer.writerow([key, val[i], disease_symptom_count[key]])

In [ ]:
# Read Cleaned Data as DF
df = pd.read_csv('/content/cleaned_data.csv')           #membaca data csv cleaned_data.csv
df.columns = ['disease', 'symptom', 'occurence_count']  #mengubah nama kolom
df.head()                                               #menampilkan hasil kolom

disease              symptom  occurence_count
0  hypertensive disease  shortness of breath           3363.0
1  hypertensive disease            dizziness           3363.0
2  hypertensive disease             asthenia           3363.0
3  hypertensive disease                 fall           3363.0
4  hypertensive disease              syncope           3363.0

In [ ]:
# Remove any rows with empty values
df.replace(float('nan'), np.nan, inplace=True)   #mengganti nilai yang kosong/Nan
df.dropna(inplace=True)                          #menghapus baris yang mengandung nilai kosong/Nan

In [ ]:
from sklearn import preprocessing                #mengimport module preprocessing dari scikit-learn

In [ ]:
n_unique = len(df['symptom'].unique())           #memperoleh nilai uniq untuk kolom symptom
n_unique                                         #menyimpan data

404

In [ ]:
df.dtypes                                       #melihat tipe data

disease             object
symptom             object
occurence_count    float64
dtype: object

In [ ]:
# Encode the Labels
from sklearn.preprocessing import LabelEncoder                #mengimport modul LabelEncoder dari sklearn.preprocessing
from sklearn.preprocessing import OneHotEncoder               #mengimport OneHotEncoder dari sklearn.preprocessing

label_encoder = LabelEncoder()                                #membuat sebuah objek LabelEncoder untuk menampung data
integer_encoded = label_encoder.fit_transform(df['symptom'])  #memberikan kode untuk nilai data symptom
print(integer_encoded)                                        #mencetak hasil

[328  87  28 ... 361 130 122]


In [ ]:
# One Hot Encode the Labels
onehot_encoder = OneHotEncoder(sparse=False)                         #Menginisialisasi objek OneHotEncoder
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)   #Mereshape array input integer_encoded agar memiliki satu kolom menggunakan .reshape(len(integer_encoded) menjadi 2D
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)       #melakukan one-hot encoding menggunakan metode fit_transform() dari objek OneHotEncoder
print(onehot_encoded)                                                #mencetak hasil

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
onehot_encoded[0]                                                  # memberikan jumlah fitur atau kategori unik yang dihasilkan setelah one-hot encoding.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
len(onehot_encoded[0])                              # memberikan jumlah fitur atau kategori unik yang dihasilkan setelah one-hot encoding.

404

In [ ]:
cols = np.asarray(df['symptom'].unique())    #mengambil nilai unik dari kolom 'symptom' dalam dataframe df dan menyimpannya dalam array cols
cols                                         #berisi daftar nilai unik dari kolom 'symptom'.

array(['shortness of breath', 'dizziness', 'asthenia', 'fall', 'syncope',
       'vertigo', 'sweat', 'sweating increased', 'palpitation', 'nausea',
       'angina pectoris', 'pressure chest', 'polyuria', 'polydypsia',
       'pain chest', 'orthopnea', 'rale', 'unresponsiveness',
       'mental status changes', 'vomiting', 'labored breathing',
       'feeling suicidal', 'suicidal', 'hallucinations auditory',
       'feeling hopeless', 'weepiness', 'sleeplessness',
       'motor retardation', 'irritable mood', 'blackout',
       'mood depressed', 'hallucinations visual', 'worry', 'agitation',
       'tremor', 'intoxication', 'verbal auditory hallucinations',
       'energy increased', 'difficulty', 'nightmare',
       'unable to concentrate', 'homelessness', 'hypokinesia',
       'dyspnea on exertion', 'chest tightness', 'cough', 'fever',
       'decreased translucency', 'productive cough', 'pleuritic pain',
       'yellow sputum', 'breath sounds decreased', 'chill', 'rhonchus',
       '

In [ ]:
# Create a new dataframe to save OHE labels
df_ohe = pd.DataFrame(columns = cols)        #membuat dataframe dengan kolom-kolom yang sesuai dengan nilai unik dari kolom 'symptom'
df_ohe.head()                                #mencetak dataframe kosong dengan kolom-kolom yang telah ditentukan sesuai dengan nilai unik dari kolom 'symptom

Empty DataFrame
Columns: [shortness of breath, dizziness, asthenia, fall, syncope, vertigo, sweat, sweating increased, palpitation, nausea, angina pectoris, pressure chest, polyuria, polydypsia, pain chest, orthopnea, rale, unresponsiveness, mental status changes, vomiting, labored breathing, feeling suicidal, suicidal, hallucinations auditory, feeling hopeless, weepiness, sleeplessness, motor retardation, irritable mood, blackout, mood depressed, hallucinations visual, worry, agitation, tremor, intoxication, verbal auditory hallucinations, energy increased, difficulty, nightmare, unable to concentrate, homelessness, hypokinesia, dyspnea on exertion, chest tightness, cough, fever, decreased translucency, productive cough, pleuritic pain, yellow sputum, breath sounds decreased, chill, rhonchus, green sputum, non-productive cough, wheezing, haemoptysis, distress respiratory, tachypnea, malaise, night sweat, jugular venous distention, dyspnea, dysarthria, speech slurred, facial paresis, hemiplegia, seizure, numbness, symptom aggravating factors, st segment elevation, st segment depression, t wave inverted, presence of q wave, chest discomfort, bradycardia, pain, nonsmoker, erythema, hepatosplenomegaly, pruritus, diarrhea, abscess bacterial, swelling, apyrexial, dysuria, hematuria, renal angle tenderness, lethargy, hyponatremia, hemodynamically stable, difficulty passing urine, consciousness clear, guaiac positive, monoclonal, ecchymosis, tumor cell invasion, haemorrhage, pallor, ...]
Index: []

[0 rows x 404 columns]

In [ ]:
for i in range(len(onehot_encoded)):       #loop untuk memasukan setiap baris dari array onehot_encoded ke dalam dataframe df_ohe
    df_ohe.loc[i] = onehot_encoded[i]

In [ ]:
df_ohe.head()        # menampilkan beberapa baris pertama dari DataFrame df_ohe, yang sudah berisi data hasil one-hot encoding dari kolom 'symptom'.

shortness of breath  dizziness  asthenia  fall  syncope  vertigo  sweat  \
0                  0.0        0.0       0.0   0.0      0.0      0.0    0.0   
1                  0.0        0.0       0.0   0.0      0.0      0.0    0.0   
2                  0.0        0.0       0.0   0.0      0.0      0.0    0.0   
3                  0.0        0.0       0.0   0.0      0.0      0.0    0.0   
4                  0.0        0.0       0.0   0.0      0.0      0.0    0.0   

   sweating increased  palpitation  nausea  ...  feces in rectum  prodrome  \
0                 0.0          0.0     0.0  ...              0.0       0.0   
1                 0.0          0.0     0.0  ...              0.0       0.0   
2                 0.0          0.0     0.0  ...              0.0       0.0   
3                 0.0          0.0     0.0  ...              0.0       0.0   
4                 0.0          0.0     0.0  ...              0.0       0.0   

   hypoproteinemia  alcohol binge episode  abdomen acute  air fluid level  \
0              0.0                    0.0            0.0              0.0   
1              0.0                    0.0            0.0              0.0   
2              0.0                    0.0            0.0              0.0   
3              0.0                    0.0            0.0              0.0   
4              0.0                    0.0            0.0              0.0   

   catching breath  large-for-dates fetus  immobile  homicidal thoughts  
0              0.0                    0.0       0.0                 0.0  
1              0.0                    0.0       0.0                 0.0  
2              0.0                    0.0       0.0                 0.0  
3              0.0                    0.0       0.0                 0.0  
4              0.0                    0.0       0.0                 0.0  

[5 rows x 404 columns]

In [ ]:
len(df_ohe)                         #memberikan jumlah fitur atau kategori unik yang dihasilkan setelah one-hot encoding.

2126

In [ ]:
# Disease Dataframe
df_disease = df['disease']   #membuat DataFrame df_disease yang berisi kolom 'disease' dari DataFrame df. df['disease']
df_disease.head()            #menampilkan beberapa baris pertama dari kolom 'disease'

0    hypertensive disease
1    hypertensive disease
2    hypertensive disease
3    hypertensive disease
4    hypertensive disease
Name: disease, dtype: object

In [ ]:
# Concatenate OHE Labels with the Disease Column
df_concat = pd.concat([df_disease,df_ohe], axis=1)  #menggabungkan kolom 'disease' dari DataFrame df_disease dengan DataFrame df_ohe, yang berisi hasil one-hot encoding dari kolom 'symptom
df_concat.head()                                    #mendapatkan DataFrame df_concat yang berisi kolom 'disease' dan hasil one-hot encoding dari kolom 'symptom', yang telah digabungkan bersama

disease  shortness of breath  dizziness  asthenia  fall  \
0  hypertensive disease                  0.0        0.0       0.0   0.0   
1  hypertensive disease                  0.0        0.0       0.0   0.0   
2  hypertensive disease                  0.0        0.0       0.0   0.0   
3  hypertensive disease                  0.0        0.0       0.0   0.0   
4  hypertensive disease                  0.0        0.0       0.0   0.0   

   syncope  vertigo  sweat  sweating increased  palpitation  ...  \
0      0.0      0.0    0.0                 0.0          0.0  ...   
1      0.0      0.0    0.0                 0.0          0.0  ...   
2      0.0      0.0    0.0                 0.0          0.0  ...   
3      0.0      0.0    0.0                 0.0          0.0  ...   
4      0.0      0.0    0.0                 0.0          0.0  ...   

   feces in rectum  prodrome  hypoproteinemia  alcohol binge episode  \
0              0.0       0.0              0.0                    0.0   
1              0.0       0.0              0.0                    0.0   
2              0.0       0.0              0.0                    0.0   
3              0.0       0.0              0.0                    0.0   
4              0.0       0.0              0.0                    0.0   

   abdomen acute  air fluid level  catching breath  large-for-dates fetus  \
0            0.0              0.0              0.0                    0.0   
1            0.0              0.0              0.0                    0.0   
2            0.0              0.0              0.0                    0.0   
3            0.0              0.0              0.0                    0.0   
4            0.0              0.0              0.0                    0.0   

   immobile  homicidal thoughts  
0       0.0                 0.0  
1       0.0                 0.0  
2       0.0                 0.0  
3       0.0                 0.0  
4       0.0                 0.0  

[5 rows x 405 columns]

In [ ]:
df_concat.drop_duplicates(keep='first',inplace=True)    #menghapus baris-baris duplikat dari DataFrame df_concat

In [ ]:
df_concat.head()                                   #menampilkan beberapa baris pertama dari DataFrame df_concat yang sudah tidak memiliki baris duplikat lagi.

disease  shortness of breath  dizziness  asthenia  fall  \
0  hypertensive disease                  0.0        0.0       0.0   0.0   
1  hypertensive disease                  0.0        0.0       0.0   0.0   
2  hypertensive disease                  0.0        0.0       0.0   0.0   
3  hypertensive disease                  0.0        0.0       0.0   0.0   
4  hypertensive disease                  0.0        0.0       0.0   0.0   

   syncope  vertigo  sweat  sweating increased  palpitation  ...  \
0      0.0      0.0    0.0                 0.0          0.0  ...   
1      0.0      0.0    0.0                 0.0          0.0  ...   
2      0.0      0.0    0.0                 0.0          0.0  ...   
3      0.0      0.0    0.0                 0.0          0.0  ...   
4      0.0      0.0    0.0                 0.0          0.0  ...   

   feces in rectum  prodrome  hypoproteinemia  alcohol binge episode  \
0              0.0       0.0              0.0                    0.0   
1              0.0       0.0              0.0                    0.0   
2              0.0       0.0              0.0                    0.0   
3              0.0       0.0              0.0                    0.0   
4              0.0       0.0              0.0                    0.0   

   abdomen acute  air fluid level  catching breath  large-for-dates fetus  \
0            0.0              0.0              0.0                    0.0   
1            0.0              0.0              0.0                    0.0   
2            0.0              0.0              0.0                    0.0   
3            0.0              0.0              0.0                    0.0   
4            0.0              0.0              0.0                    0.0   

   immobile  homicidal thoughts  
0       0.0                 0.0  
1       0.0                 0.0  
2       0.0                 0.0  
3       0.0                 0.0  
4       0.0                 0.0  

[5 rows x 405 columns]

In [ ]:
len(df_concat)                           #memberikan jumlah baris dalam DataFrame df_concat setelah menghapus duplikat

2097

In [ ]:
cols = df_concat.columns    #mendapatkan array yang berisi nama-nama kolom dari DataFrame df_concat
cols                        #menampilkan array yang berisi nama-nama kolom dari DataFrame df_concat

Index(['disease', 'shortness of breath', 'dizziness', 'asthenia', 'fall',
       'syncope', 'vertigo', 'sweat', 'sweating increased', 'palpitation',
       ...
       'feces in rectum', 'prodrome', 'hypoproteinemia',
       'alcohol binge episode', 'abdomen acute', 'air fluid level',
       'catching breath', 'large-for-dates fetus', 'immobile',
       'homicidal thoughts'],
      dtype='object', length=405)

In [ ]:
cols = cols[1:]             # mendapatkan subset dari array cols, dimulai dari indeks ke-1 hingga akhir

In [ ]:
# Since, every disease has multiple symptoms, combine all symptoms per disease per row
df_concat = df_concat.groupby('disease').sum()  #mengelompokkan berdasarkan kolom 'disease' dan jumlahkan nilai gejalanya
df_concat = df_concat.reset_index()             #mengembalikan indeks DataFrame ke bentuk awalnya setelah pengelompokan
df_concat[:5]                                   #menampilkan beberapa baris pertama dari DataFrame yang sudah dimodifikasi.

disease  shortness of breath  dizziness  \
0                  Alzheimer's disease                  0.0        0.0   
1                                  HIV                  0.0        0.0   
2       Pneumocystis carinii pneumonia                  0.0        0.0   
3             accident cerebrovascular                  0.0        0.0   
4  acquired immuno-deficiency syndrome                  0.0        0.0   

   asthenia  fall  syncope  vertigo  sweat  sweating increased  palpitation  \
0       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
1       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
2       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
3       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   
4       0.0   0.0      0.0      0.0    0.0                 0.0          0.0   

   ...  feces in rectum  prodrome  hypoproteinemia  alcohol binge episode  \
0  ...              0.0       0.0              0.0                    0.0   
1  ...              0.0       0.0              0.0                    0.0   
2  ...              0.0       0.0              0.0                    0.0   
3  ...              0.0       0.0              0.0                    0.0   
4  ...              0.0       0.0              0.0                    0.0   

   abdomen acute  air fluid level  catching breath  large-for-dates fetus  \
0            0.0              1.0              0.0                    0.0   
1            0.0              0.0              0.0                    0.0   
2            0.0              0.0              0.0                    0.0   
3            0.0              0.0              0.0                    0.0   
4            0.0              0.0              0.0                    0.0   

   immobile  homicidal thoughts  
0       0.0                 0.0  
1       0.0                 0.0  
2       0.0                 1.0  
3       0.0                 0.0  
4       0.0                 0.0  

[5 rows x 405 columns]

In [ ]:
len(df_concat)         #menampilkan jumlah penyakit yang ada setelah proses pengelompokan dan penjumlahan gejala

149

In [ ]:
df_concat.to_csv("/content/training_dataset.csv", index=False)   #menyimpan ke dalam file CSV dengan nama "training_dataset.csv" tanpa menyertakan indeks DataFrame

In [ ]:
# One Hot Encoded Features
X = df_concat[cols]   #menggunakan kolom-kolom one-hot encoded (disebut cols) dari DataFrame df_concat

# Labels
y = df_concat['disease']   #memprediksi penyakit berdasarkan gejala-gejala yang diberikan

## Model Training

In [ ]:
from sklearn.model_selection import train_test_split                ##import module train_test split dari sckitlearn untuk membagi dataset
from sklearn.naive_bayes import MultinomialNB                       #import MultinomialNB dari naive bayes
from sklearn import tree                                            #import module tree dari decision tree classifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz    #import DecisionTreeClassifier untuk membuat model tree, export_graphviz untuk menyimpan visualisasi

In [ ]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)      #membagi dataset test dan train dengan test_size 0,2 dan random_state 101

In [ ]:
len(X_train), len(y_train)          #mengecek panjang data masing masing dari data train

(119, 119)

In [ ]:
len(X_test), len(y_test)             #mengecek panjang data masing masing dari data test

(30, 30)

In [ ]:
dt = DecisionTreeClassifier()        #membuat kelas dt untuk DecisionTreeClassifier
clf_dt=dt.fit(X, y)                  #melatih model x dan y

In [ ]:
clf_dt.score(X, y)                   #menghitung akurasi model

0.9731543624161074

In [ ]:
export_graphviz(dt,                 #menyimpan dan menvisualisasikan hasil dari decisionTreeClassifier
                out_file='./tree.dot',
                feature_names=cols)

In [ ]:
!pip install graphviz          #menginstall graphviz

In [ ]:
from graphviz import Source      #mengimport source dari graphviz
from sklearn import tree         #mengimport tree dari sklearn

#Membuat visualisasi dari decision tree ke format png
graph = Source(export_graphviz(dt,
                out_file=None,
                feature_names=cols))

png_bytes = graph.pipe(format='png')

with open('tree.png','wb') as f:
    f.write(png_bytes)

In [ ]:
from IPython.display import Image       #menampilkan gambar menggunakan byte dari file PNG
Image(png_bytes)

In [ ]:
disease_pred = clf_dt.predict(X)      #memperediksi dataset x

In [ ]:
disease_real = y.values                #mengakses nilai target sebenarnya

In [ ]:
#memastikan prediksi yang dihasilkan oleh model tidak sama dengan nilai target sebenarnya
for i in range(0, len(disease_real)):
    if disease_pred[i]!=disease_real[i]:
        print ('Pred: {0}\nActual: {1}\n'.format(disease_pred[i], disease_real[i]))

Pred: coronary arteriosclerosis
Actual: coronary heart disease

Pred: depression mental
Actual: depressive disorder

Pred: malignant neoplasms
Actual: primary malignant neoplasm

Pred: septicemia
Actual: systemic infection

